### ISSUE TITLE
Create test cases for hashcat API calls

### ISSUE THREAD

**Issue by Rich5** [Rich5/pyhashcat#11]
We need a comprehensive list of tests to make sure all the features of hashcat have been implemented in into pyhashcat bindings.

- Test all attack modes
- Test outputs

**Comment by sam97** [comment]
Was there any particular testing tool you had in mind? Or just a simple script that calls all the modes is enough (along with a list of plaintext-hash pairs to test on)? I'll see if I can get a set of basic tests compiled.

**Comment by Rich5** [comment]
Just scripts to test the all the functionality.  Attack modes, I/O, events with callbacks, etc. Any help would be great since hashcat has so many features.
