### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by Rich5** [Rich5/pyhashcat#12]
Once the Python 2 bindings are finished need to port to Python 3. This is a placeholder issue.

**Comment by matlink** [comment]
any ETA? How hard it seems to be?

**Comment by Rich5** [comment]
I'll start working on this once pyhashcat 2.0 final is released. There are number of changes that need to happen before porting. It's not hard, but it does require some effort. The Python C API changed a lot from 2to3

**Comment by mcoates1** [comment]
Is there any update on this? Looking to use it for a group project in one of my classes. Currently using python 3.6.
