### ISSUE TITLE
test.py RuntimeError

### ISSUE THREAD

**Issue by Vepnar** [Rich5/pyhashcat#26]
i tried to use your test.py but this error occurred, I dont what is wrong about `sleep(5)`
```
-------------------------------
---- Simple pyhashcat Test ----
-------------------------------
[!] Hashcat object init with id:  140440595707256
[!] cb_id cracked:  1001
[!] cb_id finished:  1002
[!] cb_id benchmark_status:  1003
[+] Running hashcat
STATUS:  Initializing
Traceback (most recent call last):
  File "test.py", line 93, in <module>
    sleep(5)
RuntimeError
```

**Comment by harrim4n** [comment]
The error location is misleading because of multithreading.
I would guess that hashcat is unable to run because of some issue.
Have you tried running hashcat manually?
`hashcat --benchmark`

**Comment by Rich5** [comment]
closing since there is no response from op.
