### ISSUE TITLE
Parsing output and then pushing input

### ISSUE THREAD

**Issue by THEMVFFINMAN** [Rich5/pyHashcat#9]
I'm trying to get the output, check when the gpu temperature is a certain level, and then send a pause command to oclhashcat. As far as I can tell this doesn't really help for input right?

**Comment by Rich5** [comment]
Sorry this repo hasn't been kept up to date lately. Getting gpu temp is tricky. At the time this was last updated you had to create a stream gobbler as mentioned in the readme, and then parse the output for the gpu temp. Not the best solution I know. As for pausing and then restoring you can issue the stop command to end the process. This should generate a restore file, and then you can start it again with the session switch. I don't use sessions often so if this doesn't work I'll make an issue and address it in the next release when I get time. Hope this helps.
